[Desktop Entry]
Name=Absolute Luna
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=Absolute Luna
MetacityTheme=Absolute Luna
IconTheme=Faenza
GtkColorScheme=fg_color:#1a1a1a1a1a1a,bg_color:#e147dbf9d604,text_color:#000000000000,base_color:#fd70fc2cfae6,selected_fg_color:#ffffffffffff,selected_bg_color:#8fc7a821c51e,tooltip_fg_color:#000000000000,tooltip_bg_color:#f5f5f5f5c9c9
CursorTheme=default
CursorSize=18
